### ISSUE TITLE
PyJWT 2.0.0 breaks the library

### ISSUE THREAD

**Issue by eroshin-n** [Fatal1ty/aioapns#21]
Using this library with the latest version of PyJWT (2.0.0) yields an error 

`AttributeError: 'str' object has no attribute 'decode'`

The source of the error is this line: https://github.com/Fatal1ty/aioapns/blob/master/aioapns/connection.py#L65

Everything works fine with PyJWT==1.7.1 or with PyJWT==2.0.0 if you remove decoding

Can we either remove the `.decode('ascii')` or freeze the PyJWT version?

**Comment by Fatal1ty** [comment]
Hi @eroshin-n. Can you test aioapns with PyJWT>=2.0.0 and removed .decode('ascii')? I want to update requirements but I don't have a developer account at the moment to test it properly.

**Comment by eroshin-n** [comment]
@Fatal1ty Hello! Sorry for a late response; I can confirm that aioapns works with PyJWT>=2.0.0 and removed `.decode('ascii')`

As mentioned in #23: freezing PyJWT version below 2.0.0 is definitely the quickest and safest choice AND it works for python2 as well

**Comment by Fatal1ty** [comment]
Sorry for delayed answer. I released 2.0.1 version with updated dependencies.
